version: '3'

volumes:
  db_data:

services:
  php:
    build: ./.devops/php-fpm
    volumes:
      - './:/var/www/app'
      - './.devops/php-fpm/php.ini:/usr/local/etc/php/conf.d/docker-app.ini'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    links:
      - mysql
    depends_on:
      - mysql

  nginx:
    image: 'nginx:alpine'
    volumes:
      - './.devops/nginx/app.conf:/etc/nginx/conf.d/app.conf'
      - './:/var/www/app'
    ports:
      - '8080:8080'
    links:
      - php
    depends_on:
      - php

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=default
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping --silent --user=root --password=$$MYSQL_ROOT_PASSWORD

  pma:
    image: phpmyadmin
    environment:
      - PMA_ARBITRARY=
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
      - '5050:80'
    links:
      - mysql
    depends_on:
      - mysql
